### ISSUE TITLE
Best approach to verify props pass through

### ISSUE THREAD

**Issue by Whoaa512** [kentcdodds/react-testing-library#23] opened 2018-03-26 19:43 UTC
I have a component which should pass props through to it's child. What's the best way to verify this?

```js
import React, { PureComponent } from 'react'
import classnames from 'classnames'

import styles from './styles.css'

export default class Box extends PureComponent {
    render() {
        const {
            children,
            className,
            direction,
            element: Elem = 'div',
            ...props
        } = this.props
        const _className = classnames([
            className,
            direction && styles[direction],
        ])

        return (
            <Elem className={_className} {...props}>
                {children}
            </Elem>
        )
    }
}
```

My current solution is to pass a `data-` prop but feels like there should be a better way.

```js
import _ from 'lodash'
import React from 'react'
import { render } from 'react-testing-library'

import Box from '../index'

test('pass through props', () => {
    const { container } = render(
        <Box data-my-custom-prop="my-custom-prop">
            <div>foo</div>
        </Box>,
    )

    expect(container.firstChild.dataset).toMatchSnapshot()
})
```

**Comment by kentcdodds** [comment] 2018-03-27 04:13
Hi @Whoaa512,

That seems like a fine way IMO. Though [I probably wouldn't use `toMatchSnapshot`](https://blog.kentcdodds.com/effective-snapshot-testing-e0d1a2c28eca). Also, I'd recommend not concerning yourself with testing at this level necessarily. Rather than testing the box component, just test something else that uses this feature of the box component and if that works, then you can assume the box component works.

Either way, your current test isn't all that bad :) I just wouldn't recommend the snapshot :+1:

I'm going to go ahead and close this as it's not actionable for the library :)

**Closed by kentcdodds** 2018-03-27 04:13 UTC

**Comment by MatejMazur** [comment] 2018-04-18 20:50
Hi, I have only one similar question: how should I test that my input sets the correct initial value (empty string) for an undefined value?

Thanks in advance and thanks for your great lib! 👍

**Comment by kentcdodds** [comment] 2018-04-18 23:10
I'd probably render the component then assert that the input has an empty string for its `value`.

**Comment by MatejMazur** [comment] 2018-04-19 05:36
Sorry I mean how can you prevent (with a test) from the accidental forgetted initial value for the input if this input gets undefined value. Because if another contributor rewrites my component with an input and he forgot to assign an empty string to the value then he doesn't see any failure in tests and he happily pulls a request without knowing it.

**Comment by kentcdodds** [comment] 2018-04-19 05:39
I'm sorry, I'm not sure I follow the problem. Could you please reproduce what you're talking about in [a codesandbox](https://codesandbox.io/s/5z6x4r7n0p)?

**Comment by MatejMazur** [comment] 2018-04-28 16:02
Sorry for my late response.
If you don't specify an initial value with a string (e.g. initial value of foo was undefined `state.foo = undefined => called onChange => state.foo = 'a'`) of an input then React warns you:
```
Input is changing a uncontrolled input of type text to be controlled. 
Input elements should not switch from uncontrolled to controlled (or vice versa). 
Decide between using a controlled or uncontrolled input element for the lifetime of the component. 
More info: https://fb.me/react-controlled-components
```
So I thought that it would be cool if you provide some test which prevents this case. What would you do?

**Comment by kentcdodds** [comment] 2018-04-28 20:27
If you can show me a specific example of such a component I'll try to help you out.

**Comment by FauzanKhan** [comment] 2019-10-15 08:57
@kentcdodds Following up on this, how would you recommend, we verify props that are not primitive types - objects, functions?

**Comment by kentcdodds** [comment] 2019-10-15 15:38
Hi @FauzanKhan,

The best place for questions like this is on https://spectrum.chat/testing-library/help-react

It's best if you can give a https://codesandbox.io example of what you're trying to do.

**Comment by alexkrolick** [comment] 2019-10-15 18:06
`jest.spyOn` can be a good solution for checking if a dependent function component is called with certain props
