### ISSUE TITLE
Hooks render inside Jest unlike in the browser

### ISSUE THREAD

**Issue by vlad-zhukov** [kentcdodds/react-testing-library#245] opened 2018-12-12 16:29 UTC
- `react-testing-library` version: 5.3.0+
- `react` version: 16.7.0-alpha.2
- `node` version: n/a
- `npm` (or `yarn`) version: n/a

### Relevant code or config:

https://codesandbox.io/s/lp702xjv8z

```js
import React from "react";
import { render, cleanup } from "react-testing-library";
import { App, RootConsumer } from "../hello";

afterEach(cleanup);

it("should not have root!", () => {
  const { container } = render(
    <App>
      <RootConsumer />
    </App>
  );
  expect(container.innerHTML).toMatch(/I don't have the root yet/); // FAILS
});
```

### What you did:

Working with hooks I've stumbled in a use case when I need to pass a reference to a DOM element down the tree through the context (but this detail doesn't matter, it could be just a prop instead of context), and in order to propagate the change a rerender is needed. (See the CodeSandbox example.)

However if I render the same element with the `react-testing-library` this rerender in not required, which means the behaviour is different from how it works in the browser.

(It probably stands true for non-hook components too, I'll check later)

### Reproduction:

I couldn't reproduce it in CodeSandbox, is it because tests run in browser there?

**Comment by kentcdodds** [comment] 2018-12-12 17:49
Hi @vlad-zhukov,

Have you see the [`flushEffects`](https://github.com/kentcdodds/react-testing-library#flusheffects-experimental) function?

Yes, there's a difference between jsdom and the browser with `useEffect` and I'm not sure what the issue is, nor am I working on fixing it. You're welcome to do some [digging](http://kcd.im/dig), but the fix will not be in this project, so I'm going to go ahead and close this. Thanks!

**Closed by kentcdodds** 2018-12-12 17:49 UTC
